name = "Pkg"
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
keywords = ["package management"]
license = "MIT"
desc = "The next-generation Julia package manager."
version = "1.13.0"

[workspace]
projects = ["test", "docs"]

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Resolver = "ecd60e94-5748-11e9-04dc-1fe0f95e4121"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[weakdeps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[sources]
Resolver = {rev = "main", url = "https://github.com/StefanKarpinski/Resolver.jl/"}

[extensions]
REPLExt = "REPL"

[compat]
Artifacts = "1.11"
Dates = "1.11"
Downloads = "1.6"
FileWatching = "1.11"
LibGit2 = "1.11"
Libdl = "1.11"
Logging = "1.11"
Markdown = "1.11"
Printf = "1.11"
REPL = "1.11"
Random = "1.11"
SHA = "0.7"
TOML = "1"
Tar = "1.10"
UUIDs = "1.11"
julia = "1.12"
p7zip_jll = "17.5"
